import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";
import { getServerAuthSession } from "@/server/auth";
import AuthProvider from "./providers/session-provider";
import { Toaster } from "sonner";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerAuthSession();
    return (
        <html lang="en">
            <body className={`font-sans ${inter.variable}`} suppressHydrationWarning={true}>
                <AuthProvider session={session}>
                    <TRPCReactProvider>{children}</TRPCReactProvider>
                </AuthProvider>
                <Toaster
                    richColors
                    expand
                    toastOptions={{
                        classNames: {
                            toast: "rounded-none shadow",
                            title: "text-base tracking-wide",
                            description: "text-base tracking-wide",
                        },
                    }}
                />
            </body>
        </html>
    );
}
